name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - uses: actions/checkout@v3
    - name: get-image-version
      run: sh ./scripts/get-version.sh
      env:
        OAUTH: ${{ secrets.OAUTH }}
        REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
        IMAGE_NAME: backend

    - name: deploy-docker-backend
      run: sh ./scripts/deploy.sh
      env:
        OAUTH: ${{ secrets.OAUTH }}
        REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
        VERSION_NUMBER: ${{ env.NEW_VERSION }}
