name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Add certs
      run: sh ./scripts/add-certs.sh
      env:
        KEY: ${{ secrets.KEY }}
        CERTS: ${{ secrets.CERTS }}
        AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}

    - name: Build with Maven
      run: mvn -B -DskipTests=true clean compile package 
      env:
        CLUSTER_ID: ${{ secrets.CLUSTER_ID }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: get-image-version
      run: sh ./scripts/get-version.sh
      env:
        OAUTH: ${{ secrets.OAUTH }}
        REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
        IMAGE_NAME: backend

    - name: deploy-docker-backend
      run: sh ./scripts/deploy.sh
      env:
        API_KEY: ${{ secrets.API_KEY }}
        OAUTH: ${{ secrets.OAUTH }}
        REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
        VERSION_NUMBER: ${{ env.NEW_VERSION }}
        CLUSTER_ID: ${{ secrets.CLUSTER_ID }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
